### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by Evelynpa** [Evelynpa/extract-links-from-md#10]
## Creado para prueba funcional de test con Mocha.js y Chai.js
[![Mocha_JS.jpg](https://s9.postimg.org/b3x6wh0lr/Mocha_JS.jpg)](https://postimg.org/image/f0aisgll7/)

- [x] Se debe extraer link de un archivo.
- [x] Probar que sean correctos los links.

**Comment by LexisR** [comment]
La funcion del test esta corriendo y funcionando al 100%, se hizo con el ejemplo del LMS

**Comment by LexisR** [comment]
Hola, ayer hice la funcion del test que no permite leer el http con s, pero no la pondre ya que como hablamos el http sin s y el www tambien son links y no queremos restringir nuestra libreria.
