### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Evelynpa** [Evelynpa/extract-links-from-md#6]
#1  Readme
- [x] Se crea primera versión.
- [x] Se crea segunda versión.
- [x] Se crea tercera versión.
- [x] Se crea cuarta versión.

@LexisR

**Comment by LexisR** [comment]
Se modifico el readme seǵun las correcciones :+1:

**Comment by LexisR** [comment]
Eve, como te comente ayer estoy trabajando en la seccion de documentso del readme, si se te ocurre al gun formato aparte del conversado por favor enviamelo.
