### ISSUE TITLE
Modulo extract-link-from-md

### ISSUE THREAD

**Issue by Evelynpa** [Evelynpa/extract-links-from-md#9]
Modulo empleado al desarrollo de la función que obtenga los Links y texto descriptivo.

- [x] Obtener archivo externo.
- [x] Crear expresión regular.
- [x] Importar función para pruebas.

**Comment by LexisR** [comment]
La expresión regular ya esta al 100% :1st_place_medal:

**Comment by LexisR** [comment]
Eve, yo creo que ya estamos listas para subir nuestra version 1.1.0 npmjs. 
Pd: ya tenemos 12 descargas :) :1st_place_medal:
